<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PISMO.Core</RootNamespace>
    <AssemblyName>PISMO.Core</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- Кроссплатформенный клиент MySQL — работает на Linux/macOS/Windows -->
    <PackageReference Include="MySql.Data" Version="9.1.0" />
  </ItemGroup>

</Project>
